<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<!--NewPage-->
<html>
<head>
<!-- Generated by WebGain Javadoc 3.10.6.113 on Mon Dec 31 13:20:39 2001 -->
<a name="_top_"></a>
<title>
  Package com.heaton.bot.catbot
</title>
</head>
<body>
<pre><a href="packages.html">All Packages</a>  <a href="tree.html">Class Hierarchy</a>  <a href="AllNames.html">Index</a></pre>
<hr>
<h1>
  package com.heaton.bot.catbot
</h1>
<h2>
  <img src="/C:/VisualCafeXE/java/docs/images/class-index.gif" width=216 height=37 alt="Class Index">
</h2>
<menu>
  <li> <a href="com.heaton.bot.catbot.CatBot.html#_top_">CatBot</a>
  <li> <a href="com.heaton.bot.catbot.Recognize.html#_top_">Recognize</a>
  <li> <a href="com.heaton.bot.catbot.RecognizeCountry.html#_top_">RecognizeCountry</a>
  <li> <a href="com.heaton.bot.catbot.RecognizeLink.html#_top_">RecognizeLink</a>
</menu>
</body>
</html>
