-- Create SPIDER_WORKLOAD

CREATE TABLE SPIDER_WORKLOAD
(
  WORKLOAD_ID  INTEGER                          NOT NULL,
  HOST         INTEGER                          NOT NULL,
  URL          VARCHAR2(2083 BYTE)              NOT NULL,
  STATUS       VARCHAR2(1 BYTE)                 NOT NULL,
  DEPTH        INTEGER                          NOT NULL,
  URL_HASH     INTEGER                          NOT NULL,
  SOURCE_ID    INTEGER                          NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX IDX_STATUS ON SPIDER_WORKLOAD
(STATUS)
LOGGING
NOPARALLEL;


CREATE INDEX IDX_URL_HASH ON SPIDER_WORKLOAD
(URL_HASH)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_WORKLOAD_ID ON SPIDER_WORKLOAD
(WORKLOAD_ID)
LOGGING
NOPARALLEL;


ALTER TABLE SPIDER_WORKLOAD ADD (
  CONSTRAINT PK_WORKLOAD_ID
 PRIMARY KEY
 (WORKLOAD_ID));

-- Create SPIDER_HOST

CREATE TABLE SPIDER_HOST
(
  HOST_ID    INTEGER                          NOT NULL,
  HOST       VARCHAR2(255)                    NOT NULL,
  STATUS     VARCHAR2(1 BYTE)                 NOT NULL,
  URLS_DONE  INTEGER                          NOT NULL,
  URLS_ERROR INTEGER                          NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_HOST_ID ON SPIDER_HOST
(HOST_ID)
LOGGING
NOPARALLEL;


ALTER TABLE SPIDER_HOST ADD (
  CONSTRAINT PK_HOST_ID
 PRIMARY KEY
 (HOST_ID));
 
-- Create Sequences

CREATE SEQUENCE spider_workload_seq;
CREATE SEQUENCE spider_host_seq;
